	"(start with the move marked and choose two more)": "(start with the move marked and choose two more)",
	"+1 forward": "+1 forward",
	"0-3 Conditions:": "0-3 Conditions:",
	"0–3 Conditions:": "0–3 Conditions:",
	"4 or 5 Conditions:": "4 or 5 Conditions:",
	"a cold-wrought sword, a sword of teeth, a found sword": "a cold-wrought sword, a sword of teeth, a found sword",
	"Add 1 to a stat (max stat of 3)": "Add 1 to a stat (max stat of 3)",
	"Add 1 to your roll against them (after rolling)": "Add 1 to your roll against them (after rolling)",
	"Add or subtract 1 from any roll they make (after rolling)": "Add or subtract 1 from any roll they make (after rolling)",
	"Angry": "Angry",
	"Any PC confessed their love": "Any PC confessed their love",
	"Any PC de-escalated a violent situation": "Any PC de-escalated a violent situation",
	"Any PC leapt into danger with daring and panache": "Any PC leapt into danger with daring and panache",
	"Any player used a safety tool such as the palette or Check-In Card": "Any player used a safety tool such as the palette or Check-In Card",
	"Ask a question from Figure Out a Person of anyone, anywhere, if you can name one of their deceased loved ones": "Ask a question from Figure Out a Person of anyone, anywhere, if you can name one of their deceased loved ones",
	"At any time, spend a String on someone to do one of the following:": "At any time, spend a String on someone to do one of the following:",
	"Basic Moves": "Basic Moves",
	"Big Dyke Energy": "Big Dyke Energy",
	"Call on a Toxic Power": "Call on a Toxic Power",
	"Charm or social insight. +Heart": "Charm or social insight. +Heart",
	"Choose 1": "Choose 1",
	"Choose 2": "Choose 2",
	"Choose 2 and your opponent chooses 1": "Choose 2 and your opponent chooses 1",
	"Choose 2 from the 10+ list, but choose 1 thing that goes awry": "Choose 2 from the 10+ list, but choose 1 thing that goes awry",
	"Choose 3 and your opponent chooses 1 to apply to you in response": "Choose 3 and your opponent chooses 1 to apply to you in response",
	"Clear a Condition": "Clear a Condition",
	"Cleverness or knowledge. +Wit": "Cleverness or knowledge. +Wit",
	"cleverness, knowledge": "cleverness, knowledge",
	"Clothes": "Clothes",
	"Commune with the Unseen": "Commune with the Unseen",
	"Create an opportunity for an ally through prowess or distraction": "Create an opportunity for an ally through prowess or distraction",
	"Create an opportunity for you or your allies": "Create an opportunity for you or your allies",
	"Danger Moves": "Danger Moves",
	"daring": "daring",
	"Defy Disaster": "Defy Disaster",
	"Demeanor": "Demeanor",
	"Do it with style. At the GM’s discretion, you may also learn new information, discover a new opportunity, or gain a String on someone.": "Do it with style. At the GM’s discretion, you may also learn new information, discover a new opportunity, or gain a String on someone.",
	"Each character may only spend one String to add or subtract from a given roll.": "Each character may only spend one String to add or subtract from a given roll.",
	"Each player marks XP if, during the session:": "Each player marks XP if, during the session:",
	"elegance, agility": "elegance, agility",
	"emotional awareness, expression": "emotional awareness, expression",
	"Emotional Support": "Emotional Support",
	"End of Session": "End of Session",
	"Entice": "Entice",
	"Ferocious": "Ferocious",
	"Fight": "Fight",
	"Figure Out a Person": "Figure Out a Person",
	"Finally Kiss, in a Dangerous Situation": "Finally Kiss, in a Dangerous Situation",
	"Find out what it will take to get them to do what you want (for an NPC, spending the String means they may simply agree)": "Find out what it will take to get them to do what you want (for an NPC, spending the String means they may simply agree)",
	"Flirt with or provoke your opponent and gain a String on them": "Flirt with or provoke your opponent and gain a String on them",
	"For either a PC or an NPC, if you aren’t already Smitten with them, you may choose to treat a 7–9 result as a 10+ by choosing to become Smitten with the target.": "For either a PC or an NPC, if you aren’t already Smitten with them, you may choose to treat a 7–9 result as a 10+ by choosing to become Smitten with the target.",
	"Frightened": "Frightened",
	"Gain a String on them and they choose 1": "Gain a String on them and they choose 1",
	"Gain a String on them, unless they decide instead to choose 1": "Gain a String on them, unless they decide instead to choose 1",
	"Gain insight from the GM about an obstacle facing one of you": "Gain insight from the GM about an obstacle facing one of you",
	"Get flustered and awkward": "Get flustered and awkward",
	"Give in to desire": "Give in to desire",
	"Grace": "Grace",
	"Guilty": "Guilty",
	"heart": "heart",
	"Heartstring Moves": "Heartstring Moves",
	"Heat of the Moment": "Heat of the Moment",
	"Hide something in the Unseen world": "Hide something in the Unseen world",
	"Hopeless": "Hopeless",
	"How could I get you to _____?": "How could I get you to _____?",
	"How would you feel if I _____?": "How would you feel if I _____?",
	"Hungry Unseen destroy all non-sentient life in a small area": "Hungry Unseen destroy all non-sentient life in a small area",
	"If more than two people finally kiss in these circumstances, they all get the bonus. Each participant must be enthusiastic about kissing to trigger this move.": "If more than two people finally kiss in these circumstances, they all get the bonus. Each participant must be enthusiastic about kissing to trigger this move.",
	"If the target is a PC:": "If the target is a PC:",
	"If the target is an NPC:": "If the target is an NPC:",
	"If they open up to you, they choose 1": "If they open up to you, they choose 1",
	"If they open up to you, they choose 1, and you either choose 1 or take a String on them": "If they open up to you, they choose 1, and you either choose 1 or take a String on them",
	"If they’re Smitten with you, they may choose an additional option.": "If they’re Smitten with you, they may choose an additional option.",
	"If you gain a fourth String on someone, you have a profound insight and learn something about them that even they don’t know; the player tells you what you learn, possibly asking the GM for ideas. It’s up to you whether you share that insight with the character or not. In addition, clear all but one of your Strings on them and gain 2 XP.": "If you gain a fourth String on someone, you have a profound insight and learn something about them that even they don’t know; the player tells you what you learn, possibly asking the GM for ideas. It’s up to you whether you share that insight with the character or not. In addition, clear all but one of your Strings on them and gain 2 XP.",
	"If you’re Smitten with them and they refuse to open up to you, it stings. You mark a Condition.": "If you’re Smitten with them and they refuse to open up to you, it stings. You mark a Condition.",
	"Influence With a String": "Influence With a String",
	"Insecure": "Insecure",
	"integrity, metaphysical power": "integrity, metaphysical power",
	"It answers the question and grants you +1 forward to act on the information": "It answers the question and grants you +1 forward to act on the information",
	"It answers the question and the GM chooses 1": "It answers the question and the GM chooses 1",
	"It gains a String on you": "It gains a String on you",
	"It takes something from you, either knowledge, reputation, or something physical": "It takes something from you, either knowledge, reputation, or something physical",
	"Learn something important from the Unseen": "Learn something important from the Unseen",
	"Learn the recent history of an object you hold": "Learn the recent history of an object you hold",
	"Live happily ever after": "Live happily ever after",
	"Loyal Steed": "Loyal Steed",
	"Mark XP": "Mark XP",
	"Might, endurance, or courage. +Daring": "Might, endurance, or courage. +Daring",
	"Name your steed and detail two strengths and two weaknesses from the lists given. When riding your steed, you may roll +Spirit to Fight and may take a person with you whenever you Defy Disaster.": "Name your steed and detail two strengths and two weaknesses from the lists given. When riding your steed, you may roll +Spirit to Fight and may take a person with you whenever you Defy Disaster.",
	"no": "no",
	"Offer them an XP to do something (don’t spend the String if they refuse the temptation)": "Offer them an XP to do something (don’t spend the String if they refuse the temptation)",
	"Pain is nothing to you; ignore the next time you would Stagger while transformed": "Pain is nothing to you; ignore the next time you would Stagger while transformed",
	"Promise something they think you want": "Promise something they think you want",
	"provoke them to do something foolish or harmful and take advantage of a String on them if you have one": "provoke them to do something foolish or harmful and take advantage of a String on them if you have one",
	"Restless Unseen cause a haunting": "Restless Unseen cause a haunting",
	"Shameless": "Shameless",
	"skill at arms, forcefulness": "skill at arms, forcefulness",
	"Smitten": "Smitten",
	"Special Moves": "Special Moves",
	"spirit": "spirit",
	"Stagger (Reactive Move)": "Stagger (Reactive Move)",
	"Stern Unseen judge you, inflicting a Condition": "Stern Unseen judge you, inflicting a Condition",
	"Strengths": "Strengths",
	"String Advance": "String Advance",
	"Swiftness or elegance. +Grace": "Swiftness or elegance. +Grace",
	"Switch to a new playbook": "Switch to a new playbook",
	"Sword": "Sword",
	"Take a move from any playbook": "Take a move from any playbook",
	"Take an object from your opponent or seize a superior position": "Take an object from your opponent or seize a superior position",
	"Take another move from your playbook": "Take another move from your playbook",
	"Temporarily alter the Unseen nature of a place": "Temporarily alter the Unseen nature of a place",
	"Tenacious Purpose": "Tenacious Purpose",
	"The Beast": "The Beast",
	"The Chosen": "The Chosen",
	"The Devoted": "The Devoted",
	"The GM will offer you a hard choice or success with a sacrifice.": "The GM will offer you a hard choice or success with a sacrifice.",
	"The Infamous": "The Infamous",
	"The Nature Witch": "The Nature Witch",
	"The Scoundrel": "The Scoundrel",
	"The Seeker": "The Seeker",
	"The Spooky Witch": "The Spooky Witch",
	"The Trickster": "The Trickster",
	"They choose 1": "They choose 1",
	"They give you a String on them": "They give you a String on them",
	"They mark XP if they do it": "They mark XP if they do it",
	"They mark XP if they do it, and must take a Condition if they don't": "They mark XP if they do it, and must take a Condition if they don't",
	"They take a Condition if they don't": "They take a Condition if they don't",
	"They'll do it in exchange for a small concession or reassurance": "They'll do it in exchange for a small concession or reassurance",
	"Through violence or cutting words, inflict a Condition": "Through violence or cutting words, inflict a Condition",
	"To clear, break something important to you or someone you care about": "To clear, break something important to you or someone you care about",
	"To clear, lose yourself in escapism or pleasure when you should be doing something important": "To clear, lose yourself in escapism or pleasure when you should be doing something important",
	"To clear, run away and leave something important behind": "To clear, run away and leave something important behind",
	"To clear, sacrifice something important just to hurt yourself for what you did": "To clear, sacrifice something important just to hurt yourself for what you did",
	"To clear, take rash action to confront the object of your jealousy and prove your worth without any plan or advice": "To clear, take rash action to confront the object of your jealousy and prove your worth without any plan or advice",
	"torn clothes, practical clothes, chitinous clothes, raider's clothes": "torn clothes, practical clothes, chitinous clothes, raider's clothes",
	"Tracker": "Tracker",
	"Transform": "Transform",
	"unthreatening, fast and agile, dangerous attack, hardy, stealthy, mental bond, flying (counts as both strength choices unless flight is common)": "unthreatening, fast and agile, dangerous attack, hardy, stealthy, mental bond, flying (counts as both strength choices unless flight is common)",
	"unusual diet, conspicuous, plodding, harmless, stubborn, collateral damage, vulnerable to something common": "unusual diet, conspicuous, plodding, harmless, stubborn, collateral damage, vulnerable to something common",
	"Weaknesses": "Weaknesses",
	"What are your feelings towards _____?": "What are your feelings towards _____?",
	"What do you hope to get from _____?": "What do you hope to get from _____?",
	"What do you love most?": "What do you love most?",
	"When people finally kiss after a period of tension, each takes +1 ongoing to get to safety and protect the other for the rest of the scene.": "When people finally kiss after a period of tension, each takes +1 ongoing to get to safety and protect the other for the rest of the scene.",
	"When you appeal to someone’s physical or romantic sensibilities, roll +Heart:": "When you appeal to someone’s physical or romantic sensibilities, roll +Heart:",
	"When you become Smitten with someone (always your choice), say why, give them a String on you, and answer the question in the Truths of Heart and Blade section of your playbook.": "When you become Smitten with someone (always your choice), say why, give them a String on you, and answer the question in the Truths of Heart and Blade section of your playbook.",
	"When you commit yourself to a specific goal, you may ask the GM once per scene how you could advance that goal in a way that violates “civilized” norms. Take +1 forward to act on the answer. If you refrain, it counts as an uncomfortable situation that reduces your Feral by 1 and you must mark a Condition.": "When you commit yourself to a specific goal, you may ask the GM once per scene how you could advance that goal in a way that violates “civilized” norms. Take +1 forward to act on the answer. If you refrain, it counts as an uncomfortable situation that reduces your Feral by 1 and you must mark a Condition.",
	"When you Fight, you may mark a Condition to choose an additional option, even on a 6-.": "When you Fight, you may mark a Condition to choose an additional option, even on a 6-.",
	"When you investigate a person’s living space, camp, or trail, or an object important to them, you can roll +Heart instead of +Wit to Figure Them Out, and may do so even when they’re not present. You can also ask the question, “Where did they go?” as if it were an option on the list for that move. On a 7–9, they take a String on you instead of asking a question back. Say why. Do they just smell that good or that fearsome?": "When you investigate a person’s living space, camp, or trail, or an object important to them, you can roll +Heart instead of +Wit to Figure Them Out, and may do so even when they’re not present. You can also ask the question, “Where did they go?” as if it were an option on the list for that move. On a 7–9, they take a String on you instead of asking a question back. Say why. Do they just smell that good or that fearsome?",
	"When you make it clear to your foes that you’re the biggest threat, then for the rest of the scene, whenever you roll a 10+, you may choose someone present to be impressed or intrigued with you. Once during the scene, when you gain a String on someone, gain an additional String on someone else who considers you an enemy": "When you make it clear to your foes that you’re the biggest threat, then for the rest of the scene, whenever you roll a 10+, you may choose someone present to be impressed or intrigued with you. Once during the scene, when you gain a String on someone, gain an additional String on someone else who considers you an enemy",
	"When you offer someone support in a way that could be meaningful to them, roll +Heart or +Spirit (+3 more if you spend a String on them):": "When you offer someone support in a way that could be meaningful to them, roll +Heart or +Spirit (+3 more if you spend a String on them):",
	"When you parley with a Toxic Power, ask it your question and roll +Spirit:": "When you parley with a Toxic Power, ask it your question and roll +Spirit:",
	"When you perform a ritual to commune with the Unseen, give a dangerous Unseen a String on you and roll +Spirit:": "When you perform a ritual to commune with the Unseen, give a dangerous Unseen a String on you and roll +Spirit:",
	"When you push your limits to achieve something extraordinary that’s not covered by another move, or to avert an imminent danger to yourself or someone else, say what you’re willing to sacrifice and pick your approach:": "When you push your limits to achieve something extraordinary that’s not covered by another move, or to avert an imminent danger to yourself or someone else, say what you’re willing to sacrifice and pick your approach:",
	"When you say aloud what you want from an NPC, you may give them a String on you to ask a question about them from the Figure Out move.": "When you say aloud what you want from an NPC, you may give them a String on you to ask a question about them from the Figure Out move.",
	"When you seek to incapacitate someone with violence, roll +Daring or +Grace:": "When you seek to incapacitate someone with violence, roll +Daring or +Grace:",
	"When you suffer a staggering physical or emotional blow, choose an option from the following based on the number of Conditions you have marked.": "When you suffer a staggering physical or emotional blow, choose an option from the following based on the number of Conditions you have marked.",
	"When you taunt someone into doing something they want to do but find unwise, roll +Daring:": "When you taunt someone into doing something they want to do but find unwise, roll +Daring:",
	"When you try to understand a person, roll +Wit (+3 more if you spend a String on them):": "When you try to understand a person, roll +Wit (+3 more if you spend a String on them):",
	"wild demeanor, hungry demeanor, piercing demeanor": "wild demeanor, hungry demeanor, piercing demeanor",
	"Willpower or metaphysical skill. +Spirit": "Willpower or metaphysical skill. +Spirit",
	"Wit": "Wit",
	"You are in harmony with your beast and may clear a Condition": "You are in harmony with your beast and may clear a Condition",
	"You are magnificent and little escapes your notice; you gain leverage or an opportunity with a monster": "You are magnificent and little escapes your notice; you gain leverage or an opportunity with a monster",
	"You can move in ways no ordinary person could": "You can move in ways no ordinary person could",
	"You choose 1": "You choose 1",
	"You grin and bear the blow; mark two Conditions": "You grin and bear the blow; mark two Conditions",
	"You have a bestial form, which you can assume at will and must assume whenever your Feral hits 4. When you do, tell everyone what the beast in you looks like, increase your Feral to 4 if it’s not there already, and roll +Daring:": "You have a bestial form, which you can assume at will and must assume whenever your Feral hits 4. When you do, tell everyone what the beast in you looks like, increase your Feral to 4 if it’s not there already, and roll +Daring:",
	"You hesitate or stumble and the opposition gains an opportunity": "You hesitate or stumble and the opposition gains an opportunity",
	"You mark a Condition": "You mark a Condition",
	"You may ask 2 questions, but they may ask 1 of you": "You may ask 2 questions, but they may ask 1 of you",
	"You may ask 2 questions, now or later in the scene": "You may ask 2 questions, now or later in the scene",
	"You revert to your usual form when your Feral drops below 4. While transformed, you may mark a Condition to avoid reducing your Feral, as often as you like.": "You revert to your usual form when your Feral drops below 4. While transformed, you may mark a Condition to avoid reducing your Feral, as often as you like.",
	"You’re rendered helpless for the scene": "You’re rendered helpless for the scene",
	"You’re utterly humiliated and news will spread; this could be a consequence of a setback in the confrontation, or might be caused by something you confess in the heat of the moment": "You’re utterly humiliated and news will spread; this could be a consequence of a setback in the confrontation, or might be caused by something you confess in the heat of the moment",
	"Your first five Advances must be from the top six on the list. After you take your fifth Advance, you can choose to switch to another playbook or live happily ever after. Choose one of these last two options when the emotional conflict at the core of your playbook has been resolved or eclipsed by a new conflict corresponding to a new playbook.": "Your first five Advances must be from the top six on the list. After you take your fifth Advance, you can choose to switch to another playbook or live happily ever after. Choose one of these last two options when the emotional conflict at the core of your playbook has been resolved or eclipsed by a new conflict corresponding to a new playbook.",
